### PR TITLE
Added scam category in AddScamForm.tsx

### PR DESCRIPTION
**Pull request by hanashah-01**
Initially I added scam category - rental, referring to fraudulent rental listings, but I noticed that another person has made the pull request for it. So, I changed it to vehicle, which refers to vehicle purchase scams.

### CODE REVIEW

**Comment by farhan-helmy** [comment]
Please resolve conflict TQ 🥇

**Comment by hanashah-01** [comment]
> Please resolve conflict TQ 🥇

okay, done

**Comment by farhan-helmy** [comment]
Sorry to much PR at the same file and LOC, can resolve again tq :D

**Comment by hanashah-01** [comment]
> Sorry to much PR at the same file and LOC, can resolve again tq :D

okay, done

**Pull request merged**
