### PR TITLE
Removed duplicate and added missing comma in AddScamForm.tsx

### PR DESCRIPTION
**Pull request by hanashah-01**
Removed duplicate - smartphone in scam category and added comma after scam category - advance fee.

### CODE REVIEW

**Comment by farhan-helmy** [comment]
pls resolve conflict tq!

**Comment by hanashah-01** [comment]
> pls resolve conflict tq!

okay, done

**Comment by farhan-helmy** [comment]
Sorry to much PR at the same file and LOC, can resolve again tq :D

**Comment by farhan-helmy** [comment]
can resolve aagain tq?

**Comment by hanashah-01** [comment]
> can resolve aagain tq?

ok, done

**Comment by khrnchn** [comment]
lmfao asal aku boleh merge

**Pull request merged**
