### PR TITLE
update AddScamForm.tsx, add several options for scam types

### PR DESCRIPTION
**Pull request by muhd-iqbal**

### CODE REVIEW

**Comment by farhan-helmy** [comment]
Please resolve conflict TQ 🥇

**Comment by muhd-iqbal** [comment]
@farhan-helmy resolved. And fix add missing comma

**Comment by farhan-helmy** [comment]
Sorry to much PR at the same file and LOC, can resolve again tq :D

**Comment by muhd-iqbal** [comment]
@farhan-helmy resolved :)

**Pull request merged**
