### PR TITLE
feat: add scam options

### PR DESCRIPTION
**Pull request by AfiqIzzan**
- add carousell option
- add lazada option

### CODE REVIEW

**Comment by farhan-helmy** [comment]
pls resolve conflict tq!

**Comment by AfiqIzzan** [comment]
okay, done

**Comment by AfiqIzzan** [comment]
okay, done

**Comment by farhan-helmy** [comment]
Sorry to much PR at the same file and LOC, can resolve again tq :D

**Comment by AfiqIzzan** [comment]
Done 💯

**Comment by farhan-helmy** [comment]
can resolve again? tq

**Comment by AfiqIzzan** [comment]
done

**Comment by farhan-helmy** [comment]
LGTM

**Pull request merged**
