### PR TITLE
Update AddScamForm.tsx

### PR DESCRIPTION
**Pull request by burhan3759**
1. Added 2 more scam option

### CODE REVIEW

**Comment by farhan-helmy** [comment]
Please resolve conflict TQ 🥇

**Comment by burhan3759** [comment]
> Please resolve conflict TQ 🥇

Done

**Comment by farhan-helmy** [comment]
Resolve lagi skali hahahhaa aku ada merge yg pr2 awal dulu

**Comment by burhan3759** [comment]
> Resolve lagi skali hahahhaa aku ada merge yg pr2 awal dulu

Nak merajuk dah ni, 2 line je add, 2 kali conflict dah 🤣

**Comment by farhan-helmy** [comment]
LGTM TQ HAHAhahahaha

**Pull request merged**
